service:
  data:
    data-location: "data/14300_yellow_taxidata.csv"
  flink:
    args:
#     - "--input"
#     - "/home/eleicha/Repos/BDAPRO_neu/BDAPRO_optimized_visualization_pipeline/data/1000000.csv"
#     - "--output"
#     - "data/out/"
server:
  port: 8082